// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.3
// source: watchdog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signal_Sig int32

const (
	Signal_QUIT Signal_Sig = 0
	Signal_UP   Signal_Sig = 1
)

// Enum value maps for Signal_Sig.
var (
	Signal_Sig_name = map[int32]string{
		0: "QUIT",
		1: "UP",
	}
	Signal_Sig_value = map[string]int32{
		"QUIT": 0,
		"UP":   1,
	}
)

func (x Signal_Sig) Enum() *Signal_Sig {
	p := new(Signal_Sig)
	*p = x
	return p
}

func (x Signal_Sig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal_Sig) Descriptor() protoreflect.EnumDescriptor {
	return file_watchdog_proto_enumTypes[0].Descriptor()
}

func (Signal_Sig) Type() protoreflect.EnumType {
	return &file_watchdog_proto_enumTypes[0]
}

func (x Signal_Sig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal_Sig.Descriptor instead.
func (Signal_Sig) EnumDescriptor() ([]byte, []int) {
	return file_watchdog_proto_rawDescGZIP(), []int{0, 0}
}

type Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signal Signal_Sig `protobuf:"varint,1,opt,name=signal,proto3,enum=omega.Signal_Sig" json:"signal,omitempty"`
}

func (x *Signal) Reset() {
	*x = Signal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watchdog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_watchdog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_watchdog_proto_rawDescGZIP(), []int{0}
}

func (x *Signal) GetSignal() Signal_Sig {
	if x != nil {
		return x.Signal
	}
	return Signal_QUIT
}

var File_watchdog_proto protoreflect.FileDescriptor

var file_watchdog_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6f, 0x6d, 0x65, 0x67, 0x61, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x6f, 0x6d, 0x65, 0x67, 0x61, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x2e, 0x53, 0x69, 0x67, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x17, 0x0a, 0x03,
	0x53, 0x69, 0x67, 0x12, 0x08, 0x0a, 0x04, 0x51, 0x55, 0x49, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a,
	0x02, 0x55, 0x50, 0x10, 0x01, 0x32, 0x88, 0x01, 0x0a, 0x08, 0x57, 0x61, 0x74, 0x63, 0x68, 0x64,
	0x6f, 0x67, 0x12, 0x36, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0d, 0x2e, 0x6f,
	0x6d, 0x65, 0x67, 0x61, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x1a, 0x1b, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x04, 0x50, 0x75,
	0x6c, 0x6c, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_watchdog_proto_rawDescOnce sync.Once
	file_watchdog_proto_rawDescData = file_watchdog_proto_rawDesc
)

func file_watchdog_proto_rawDescGZIP() []byte {
	file_watchdog_proto_rawDescOnce.Do(func() {
		file_watchdog_proto_rawDescData = protoimpl.X.CompressGZIP(file_watchdog_proto_rawDescData)
	})
	return file_watchdog_proto_rawDescData
}

var file_watchdog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_watchdog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_watchdog_proto_goTypes = []interface{}{
	(Signal_Sig)(0),                // 0: omega.Signal.Sig
	(*Signal)(nil),                 // 1: omega.Signal
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 3: google.protobuf.Int32Value
}
var file_watchdog_proto_depIdxs = []int32{
	0, // 0: omega.Signal.signal:type_name -> omega.Signal.Sig
	1, // 1: omega.Watchdog.Notify:input_type -> omega.Signal
	2, // 2: omega.Watchdog.Pull:input_type -> google.protobuf.StringValue
	3, // 3: omega.Watchdog.Notify:output_type -> google.protobuf.Int32Value
	2, // 4: omega.Watchdog.Pull:output_type -> google.protobuf.StringValue
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_watchdog_proto_init() }
func file_watchdog_proto_init() {
	if File_watchdog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_watchdog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watchdog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_watchdog_proto_goTypes,
		DependencyIndexes: file_watchdog_proto_depIdxs,
		EnumInfos:         file_watchdog_proto_enumTypes,
		MessageInfos:      file_watchdog_proto_msgTypes,
	}.Build()
	File_watchdog_proto = out.File
	file_watchdog_proto_rawDesc = nil
	file_watchdog_proto_goTypes = nil
	file_watchdog_proto_depIdxs = nil
}
