// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: watchdog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatchdogClient is the client API for Watchdog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchdogClient interface {
	Notify(ctx context.Context, in *Signal, opts ...grpc.CallOption) (*wrapperspb.Int32Value, error)
	Pull(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
}

type watchdogClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchdogClient(cc grpc.ClientConnInterface) WatchdogClient {
	return &watchdogClient{cc}
}

func (c *watchdogClient) Notify(ctx context.Context, in *Signal, opts ...grpc.CallOption) (*wrapperspb.Int32Value, error) {
	out := new(wrapperspb.Int32Value)
	err := c.cc.Invoke(ctx, "/omega.Watchdog/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchdogClient) Pull(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, "/omega.Watchdog/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchdogServer is the server API for Watchdog service.
// All implementations must embed UnimplementedWatchdogServer
// for forward compatibility
type WatchdogServer interface {
	Notify(context.Context, *Signal) (*wrapperspb.Int32Value, error)
	Pull(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error)
	mustEmbedUnimplementedWatchdogServer()
}

// UnimplementedWatchdogServer must be embedded to have forward compatible implementations.
type UnimplementedWatchdogServer struct {
}

func (UnimplementedWatchdogServer) Notify(context.Context, *Signal) (*wrapperspb.Int32Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedWatchdogServer) Pull(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedWatchdogServer) mustEmbedUnimplementedWatchdogServer() {}

// UnsafeWatchdogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchdogServer will
// result in compilation errors.
type UnsafeWatchdogServer interface {
	mustEmbedUnimplementedWatchdogServer()
}

func RegisterWatchdogServer(s grpc.ServiceRegistrar, srv WatchdogServer) {
	s.RegisterService(&Watchdog_ServiceDesc, srv)
}

func _Watchdog_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Signal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchdogServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omega.Watchdog/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchdogServer).Notify(ctx, req.(*Signal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watchdog_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchdogServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omega.Watchdog/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchdogServer).Pull(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// Watchdog_ServiceDesc is the grpc.ServiceDesc for Watchdog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Watchdog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omega.Watchdog",
	HandlerType: (*WatchdogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _Watchdog_Notify_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _Watchdog_Pull_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "watchdog.proto",
}
